### ISSUE TITLE
gpu opened but building index is Obviously slow

### ISSUE THREAD

**Issue by apple12358lp** [milvus-io/bootcamp#183]
My machine is 4cores,8G RAM,gtx 1080ti, when I am testing pic_search, gpu is opened,but indexing is still extremely slow.How should I take it ? It seems that gpu is not used.

**Comment by JackLCL** [comment]
Firstly, you can use "docker exec -ti <pic-search-server container> bash" to go into container. Then, you can use " pip3 show tensorflow " to confirm whether you have used gpu-version tensorflow. If not gpu-version tensorflow, you should modify the version of tensorflow in reqirement.txt. Finally you can use Dockerfile to rebuild the pic-search-webserver image.

This is my suggestion, you can have a try.

**Comment by apple12358lp** [comment]
problem solved,thank you very much.

**Comment by apple12358lp** [comment]
Sorry,I modifed tensorflow into tensorflow-gpu in requirement.txt,then build the new image,but still cannot use the gpu.what's the problem?Can you tell me more in detail? Thank you.

**Comment by JackLCL** [comment]
When you start the pic-search-webserver docker, you try adding " --gpus all " in your start command.

**Comment by apple12358lp** [comment]
`root@876b437f29a9:/app/src# pip3 show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.14.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: six, keras-applications, gast, google-pasta, protobuf, absl-py, tensorboard, termcolor, numpy, wrapt, grpcio, wheel, keras-preprocessing, astor, tensorflow-estimator
root@876b437f29a9:/app/src# nvidia-smi
Tue Apr 28 07:03:06 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
| 23%   32C    P8    18W / 250W |    145MiB / 11177MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
root@876b437f29a9:/app/src# cat app.log
2020-04-28 07:01:21,261 - tensorflow - WARNING - From app.py:31: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2020-04-28 07:01:21,262 - tensorflow - WARNING - From app.py:35: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-04-28 07:01:21,389 - tensorflow - WARNING - From app.py:48: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2020-04-28 07:01:21,417 - tensorflow - WARNING - From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

2020-04-28 07:01:21,868 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-04-28 07:03:19,059 - werkzeug - INFO - 192.168.101.2 - - [28/Apr/2020 07:03:19] "POST /api/v1/delete HTTP/1.1" 200 -
2020-04-28 07:03:28,982 - werkzeug - INFO - 192.168.101.2 - - [28/Apr/2020 07:03:28] "OPTIONS /api/v1/train HTTP/1.1" 200 -
2020-04-28 07:03:29,537 - tensorflow - WARNING - From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.
`

I listened to your suggestions,but it seems still doesn`t matter,what went wrong?

**Comment by apple12358lp** [comment]
`root@876b437f29a9:/app/src# python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))
2020-04-28 17:23:28.501297: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-04-28 17:23:28.503637: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-28 17:23:28.504245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
2020-04-28 17:23:28.504333: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-04-28 17:23:28.504407: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-04-28 17:23:28.504467: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-04-28 17:23:28.504527: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-04-28 17:23:28.504578: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-04-28 17:23:28.504629: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-04-28 17:23:28.507521: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-04-28 17:23:28.507565: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2020-04-28 17:23:28.507951: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-28 17:23:28.589854: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-28 17:23:28.590519: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4fb38a0 executing computations on platform CUDA. Devices:
2020-04-28 17:23:28.590534: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2020-04-28 17:23:28.611421: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192810000 Hz
2020-04-28 17:23:28.611712: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x533a180 executing computations on platform Host. Devices:
2020-04-28 17:23:28.611736: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-04-28 17:23:28.611806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-28 17:23:28.611822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]
root@876b437f29a9:/app/src# ls /usr/local/cuda/lib64
libOpenCL.so             libcudadevrt.a         libcufft.so.10.1.1.243   libculibos.a               libcusolverMg.so.10.2.0.243  libnvrtc-builtins.so
libOpenCL.so.1           libcudart.so           libcufftw.so.10          libcurand.so.10            libcusparse.so.10            libnvrtc-builtins.so.10.1
libOpenCL.so.1.1         libcudart.so.10.1      libcufftw.so.10.1.1.243  libcurand.so.10.1.1.243    libcusparse.so.10.3.0.243    libnvrtc-builtins.so.10.1.243
libaccinj64.so           libcudart.so.10.1.243  libcuinj64.so            libcusolver.so.10          libnvToolsExt.so             libnvrtc.so.10.1
libaccinj64.so.10.1      libcudart_static.a     libcuinj64.so.10.1       libcusolver.so.10.2.0.243  libnvToolsExt.so.1           libnvrtc.so.10.1.243
libaccinj64.so.10.1.243  libcufft.so.10         libcuinj64.so.10.1.243   libcusolverMg.so.10        libnvToolsExt.so.1.0.0       stubs
`
The tensorflow-gpu use cuda10.0 as default,but cuda10.1 is in the container,and it seems libcublas.so is not installed. What can I do?

**Comment by JackLCL** [comment]
You can install cuda in your local environment. Then you can start webserver in local environment instead of docker. I have used gpu-tensorflow to load pictures in my local environment successfully. You can have a try.

Also welcome to join our wechat group to talk more.
![image](https://user-images.githubusercontent.com/53512883/80558018-68751b80-8a0b-11ea-8a22-b8fb8ef6dad6.png)

**Comment by JackLCL** [comment]
My local environment is shown below. 
![image](https://user-images.githubusercontent.com/53512883/80558386-c81ff680-8a0c-11ea-8bc0-2ce35b7403b0.png)
![image](https://user-images.githubusercontent.com/53512883/80558406-df5ee400-8a0c-11ea-9d91-2c26ca86e0f2.png)

**Comment by apple12358lp** [comment]
Problem solved! 
replace  'From tensorflow/tensorflow' with 'From nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04' in Dockerfile.
Thank you very much.

**Comment by JackLCL** [comment]
Good! And I have also pushed a new webserver image to dockerhub named milvusbootcamp/pic-search-webserver:0.5.0.   It can solve this problem too.
